config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :zip_codes
  end
  # Add your extension routes here
end

app/models/zip_code.rb
class ZipCode < ActiveRecord::Base
  has_many :zone_members, :as => :zoneable
  has_many :zones, :through => :zone_members

  validates :value, :presence => true

  def <=>(other)
    value <=> other.value
  end

  def to_s
    value
  end

  def name
    value
  end
end

app/models/zone_decorator.rb
Zone.class_eval do
  def kind
    member = self.members.last
    case member && member.zoneable_type
    when "State"  then "state"
    when "Zone"   then "zone"
    when "Zip Code" then "zip code"
    else
      "country"
    end
  end

end

app/controllers/admin/zip_codes_controller.rb
class Admin::ZipCodesController < Admin::BaseController
  resource_controller
  new_action.response do |wants|
    wants.html {render :layout => !request.xhr?}
  end
  create.wants.html { redirect_to admin_zip_codes_url }
  update.wants.html { redirect_to admin_zip_codes_url }
=begin
  before_filter :load_data

  index.response do |wants|
    wants.html
    wants.js do
      render :partial => 'state_list.html.erb'
    end
  end



  private

    def collection
      @collection ||= end_of_association_chain.order('name')
    end

    def load_data
      @countries = Country.order('name')
    end
=end
end

app/controllers/admin/zones_controller_decorator.rb
Admin::ZonesController.class_eval do
  private
  def load_data
    @countries = Country.all.sort
    @states = State.all.sort
    @zip_codes = ZipCode.all
    @zones = Zone.all.sort
  end
end

app/views/admin/zip_codes/_form.html.erb
<%= f.field_container :value do %>
  <%= f.label :value, t("value") %><br />
  <%=f.text_field :value %>
<% end %>

app/views/admin/zip_codes/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("editing_zip_code") %></h1>

<%= render 'shared/error_messages', :target => @zip_code %>

<%= form_for(:zip_code, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => "admin/shared/edit_resource_links" %>
<% end %>

app/views/admin/zip_codes/index.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("zip_codes") %></h1>

<%= image_tag "spinner.gif", :plugin=>"spree", :style => "display:none", :id => 'busy_indicator' %>

<div id="zip-code-list">
<table class="index" id='listing_zip_codes'>
  <thead>
    <tr>
      <th><%= t("value") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @zip_codes.each do |zip_code| %>
      <tr id="<%= dom_id zip_code %>">
        <td><%=zip_code.value %></td>
        <td class="actions">
          <%=link_to_with_icon 'edit', t("edit"), edit_admin_zip_code_url(zip_code) %> &nbsp;
          <%=link_to_delete zip_code%>
        </td>
      </tr>
    <% end %>
    <% if @zip_codes.empty? %>
      <tr><td colspan="3"><%= t(:none) %></td></tr>
    <% end %>
  </tbody>
</table>
<div id="new_zip_code"></div>
<p>
  <%= button_link_to t("new_zip_code"), new_admin_zip_code_url(@zip_code), {:remote => true, :icon => 'add'} %>
</p>

</div>

app/views/admin/zip_codes/new.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<%= render 'shared/error_messages', :target => @zip_code%>


<%= form_for(:zip_code, :url => collection_url) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => "admin/shared/new_resource_links" %>
<% end %>

app/views/admin/zones/_form.html.erb
<%= zone_form.field_container :name do %>
  <%= zone_form.label :name, t("name") %><br />
  <%=zone_form.text_field :name %>
<% end %>

<%= zone_form.field_container :description do %>
  <%= zone_form.label :description, t("description") %><br />
  <%=zone_form.text_field :description %>
<% end %>

<p>
  <label><%= t("type") %></label><br />
  <label class="sub">
    <%= zone_form.radio_button("kind", "country", {:id => "country_based"}) %>
    <%= t("country_based") %>
  </label> &nbsp;
  <label class="sub">
    <%= zone_form.radio_button("kind", "state", {:id => "state_based"}) %>
    <%= t("state_based") %>
  </label> &nbsp;
  <label class="sub">
    <%= zone_form.radio_button("kind", "zip code", {:id => "zip_code_based"}) %>
    <%= t("zip_code_based") %>
  </label> &nbsp;
  <label class="sub">
    <%= zone_form.radio_button("kind", "zone", {:id => "zone_based"}) %>
    <%= t("zone_based") %>
  </label>
</p>

<%= render "member_type", :type => "country", :zone_form => zone_form %>
<%= render "member_type", :type => "state", :zone_form => zone_form %>
<%= render "member_type", :type => "zip_code", :zone_form => zone_form %>
<%= render "member_type", :type => "zone", :zone_form => zone_form %>

app/views/admin/zones/_zip_code_member.html.erb
<li>
  <%= f.hidden_field :zoneable_type, :value => "Zip Code" %>
  <%= f.collection_select(:zoneable_id, @zip_codes, :id, :value, :include_blank => true) %>
  <%= remove_nested f %>
</li>